language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  # 6.x
  - GITHUB_REPOSITORY=drupal-core DRUPAL_VERSION=6.x PROFILE=default
  # 7.x
  #- GITHUB_REPOSITORY=drupal-core DRUPAL_VERSION=7.x PROFILE=standard

before_script:
 # Install CURL extension.
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 - cd ..
 # Prepare Drupal.
 - mkdir drupal
 - cd drupal
 # Check CURL.
 - drush php-eval 'if (function_exists("curl_version")) { return "Enabled"; } else { return "Disabled"; }'
 - cp ../$GITHUB_REPOSITORY/$DRUPAL_VERSION/drupal.make drupal.make
 - drush make drupal.make .
 # Discover newly downloaded directory.
 - ls -la
 # Install Drupal.
 - drush si $PROFILE --db-url=mysql://root:@localhost/drupal --yes
 # Prepare Simpletest.
 # Patch core using patched patch.
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then cp sites/all/modules/simpletest/D6-core-simpletest.patch D6-core-simpletest.patch; fi"
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then patch -p1 -t -i D6-core-simpletest.patch; fi"
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then wget https://drupal.org/files/drupal_web_test_case.php-1781018.patch -O drupal_web_test_case.php-1781018.patch; fi"
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then patch -p1 -t -i drupal_web_test_case.php-1781018.patch; fi"
 - sh -c "if [ '$DRUPAL_VERSION' = '6.x' ]; then cp sites/all/modules/simpletest/run-tests.sh scripts/run-tests.sh; fi"
 # Drush in D6 enables wrong.
 #- drush en simpletest --yes
 - sh -c "if [ '$DRUPAL_VERSION' = '7.x' ]; then drush en simpletest --yes; else drush php-eval \"module_enable(array('simpletest'));\"; fi"
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 #- drush vset simpletest_verbose FALSE --yes
 - drush vset simpletest_verbose TRUE --yes
 # Create a directory to output results.
 - mkdir results

script: php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.16/bin/php --url 'http://127.0.0.1:8080' --verbose --all
 #drush test-run --xml --file=sites/all/modules/moopapi/core/simpletest.test --uri=http://127.0.0.1:8080

after_script:
 - cd results
 - ls -la
# Trigger testing of changes at drupal.org.
